# Generated by Django 5.1.5 on 2025-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профайл', 'verbose_name_plural': 'Профайлы'},
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Чоловік'), ('Female', 'Жінка')], max_length=6, null=True, verbose_name='Стать'),
        ),
        migrations.AddField(
            model_name='profile',
            name='receiver_newsletter',
            field=models.BooleanField(default=False, verbose_name='Згода на отримання новин'),
        ),
    ]
