# Generated by Django 5.1.5 on 2025-02-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=6, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='receiver_newsletter',
            field=models.BooleanField(default=False, verbose_name='Получать новости'),
        ),
    ]
