# Generated by Django 5.1.5 on 2025-02-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='receiver_newsletter',
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_newsletter',
            field=models.BooleanField(default=False, verbose_name='Подписка на рассылку'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женщина'), ('Other', 'Другой')], default='O', max_length=6, verbose_name='Пол'),
        ),
    ]
