# Generated by Django 5.1.5 on 2025-02-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_receiver_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женщина'), ('Other', 'Другой')], default='Other', max_length=6, verbose_name='Пол'),
        ),
    ]
