# Generated by Django 5.1.5 on 2025-02-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='course_images', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Уникальное название урока')),
                ('title', models.CharField(max_length=120, verbose_name='Название урока')),
                ('desc', models.TextField(verbose_name='Описание урока')),
                ('number', models.IntegerField(verbose_name='Номер урока')),
                ('video', models.CharField(max_length=100, verbose_name='Видео URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Какой курс?')),
            ],
        ),
    ]
