# Generated by Django 5.1.5 on 2025-02-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.png', upload_to='course_images', verbose_name='Изображение'),
        ),
    ]
