# Generated by Django 5.1.5 on 2025-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='course_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Уникальное название курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(max_length=100, verbose_name='Видео URL'),
        ),
    ]
