# Generated by Django 5.0.4 on 2025-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_desc_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('ai', 'AI'), ('design', 'Design')], default='frontend', max_length=50),
            preserve_default=False,
        ),
    ]
