# Generated by Django 5.0.4 on 2025-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_category_remove_course_category_course_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('games', 'Games'), ('web', 'Websites'), ('design', 'Design'), ('languages', 'Languages'), ('other', 'Other'), ('paid', 'Paid')], default='all', max_length=50, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
